apiVersion: v1
kind: Pod
metadata:
  name: gostardardk8s
  labels:
    app: gostardardk8s
spec:
  containers:
  - name: gostardardk8s
    image: kobebryant/gostardardk8s
---
apiVersion: v1
kind: Service
metadata:
  name: gostardardk8s
spec:
  selector:
    app: gostardardk8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
